development:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: muber_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  channel_prefix: muber_production
