development:
  adapter: redis
  url: <%= "#{ENV['REDIS_URL']}/1" %>
  channel_prefix: muber_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= "#{ENV['REDIS_URL']}/1" %>
  channel_prefix: muber_production
