default: &default
  match:
    class: AutoMatchJob
    queue: match
    schedule: every 2 minutes
  cleanup_past:
    class: DisconnectJob
    queue: disconnect
    schedule: every 15 minutes

production:
  <<: *default

development:
  <<: *default
