:concurrency: 5

:queues:
  - ['default', 1]
  - ['match', 5]
  - ['disconnect', 5]

:scheduler:
  :schedule:
    auto_match:
      cron: '0 */1 * * * *'
      class: AutoMatchJob
    disconnect:
      cron: '0 11 * * * *'
      class: DisconnectJob