default: &default
  dispatchers:
    - polling_interval: 30
      queues: [default]
      batch_size: 2
      concurrency_maintenance: false
  workers:
    - queues: [default]
      threads: 1
      processes: 1
      polling_interval: 30

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
